name: Test & Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:

  # Test job is always triggered as continuous integration
  test:
    runs-on: ubuntu-latest
    steps:
    - name: ☑️ Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: 💎 Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: 👤 Get commit info for notification
      run: |
        echo "COMMIT_ACTOR=${{ github.actor }}" | awk -F '-preview' '{print $1}' >> $GITHUB_ENV
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          head_sha=$(git rev-parse --short=8 ${{ github.event.pull_request.head.sha }})
          echo "COMMIT_SHA=$head_sha"                    >> $GITHUB_ENV
          echo "COMMIT_MESSAGE<<EOF"                     >> $GITHUB_ENV
          echo "$(git log --format=%B -n 1 $head_sha)"   >> $GITHUB_ENV
          echo "EOF"                                     >> $GITHUB_ENV
          echo "COMMIT_URL=${{ github.event.pull_request.html_url }}"   >> $GITHUB_ENV
          echo "COMMIT_LINK=${{github.repository}}#${{github.event.pull_request.number}}" >> $GITHUB_ENV
        else
          head_sha=$(git rev-parse --short=8 ${{ github.sha }})
          echo "COMMIT_SHA=$head_sha"                    >> $GITHUB_ENV
          echo "COMMIT_MESSAGE<<EOF"                     >> $GITHUB_ENV
          echo "${{ github.event.head_commit.message }}" >> $GITHUB_ENV
          echo "EOF"                                     >> $GITHUB_ENV
          echo "COMMIT_URL=https://github.com/${{github.repository}}/commit/$head_sha" >> $GITHUB_ENV
          echo "COMMIT_LINK=${{ github.repository }}#$head_sha"                        >> $GITHUB_ENV
        fi

    - name: 🔧 Build & Test
      run: |
        JEKYLL_ENV=production bundle exec jekyll build
        JEKYLL_ENV=production bundle exec jekyll doctor
        SKIP_BUILD=true       bundle exec rake test

    - name: 🆖 Notify results (Failed)
      env:
        IDOBATA_SECRETS: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
      if:   failure() && (env.IDOBATA_SECRETS != null)
      uses: mahaker/actions-idobata@v1.1.1
      with:
        hookUrl: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
        format: 'html'
        message: |
          <div>
          CI build for <a href='${{ env.COMMIT_URL }}'>${{ env.COMMIT_LINK }}</a> : <span class='label label-${{ job.status }}'>${{ job.status }}</span> (<a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>GitHub Actions</a>)<br>
          <img src='https://github.com/${{ env.COMMIT_ACTOR }}.png' class='icon-rounded' width='16' height='16'> <a href='https://github.com/${{ env.COMMIT_ACTOR }}'>${{ env.COMMIT_ACTOR }}</a>: ${{ env.COMMIT_MESSAGE }} (<a href='https://github.com/${{ github.repository }}/commit/${{ env.COMMIT_SHA }}'>${{ env.COMMIT_SHA }}</a>)
          </div>

    - name: 🆗 Notify results (Success)
      env:
        IDOBATA_SECRETS: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
      if:   success() && (env.IDOBATA_SECRETS != null)
      uses: mahaker/actions-idobata@v1.1.1
      with:
        hookUrl: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
        format: 'html'
        message: |
          <div>
          CI build for <a href='${{ env.COMMIT_URL }}'>${{ env.COMMIT_LINK }}</a> : <span class='label label-${{ job.status }}'>${{ job.status }}</span> (<a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>GitHub Actions</a>)<br>
          <img src='https://github.com/${{ env.COMMIT_ACTOR }}.png' class='icon-rounded' width='16' height='16'> <a href='https://github.com/${{ env.COMMIT_ACTOR }}'>${{ env.COMMIT_ACTOR }}</a>: ${{ env.COMMIT_MESSAGE }} (<a href='https://github.com/${{ github.repository }}/commit/${{ env.COMMIT_SHA }}'>${{ env.COMMIT_SHA }}</a>)
          </div>

  # Deploy job is triggered only pushed to main branch && CI passed
  deploy:
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: ☑️ Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: 💎 Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: 🧪 Install gems
      run: |
        bundle config set with 'test'
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3

    - name: 🔧 Build
      run: |
        JEKYLL_ENV=production bundle exec jekyll build

    - name: 🤖 Generate individual pages by projects.yml data
      run: |
        bundle exec rake upsert_project_pages_by_data
        if [ -n "$(git status ./_posts --porcelain)" ]; then
          if ( ruby -ryaml -e "p YAML.load(STDIN.read)" < _data/projects.yml > /dev/null ); then
            git config user.name  "Yohei Yasukawa"
            git config user.email "yohei@yasslab.jp"
            git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git checkout main
            git add _posts/
            git commit -m '🤖 Upsert project page(s) by GitHub Actions'
            git push origin main
          else
            echo "Detect syntax error in '_data/projects.yml' file, check its syntax."
          fi
        fi

    - name: 🚀 Deploy to GitHub Pages
      if:   github.ref == 'refs/heads/main' && job.status == 'success'
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir:    ./_site
